services:
  app:
    build: .
    image: voice-bridge-rtp-proxy
    container_name: voice-bridge-rtp-proxy
    env_file:
      - .env
    ports:
      - "3002:3002/tcp"
      - "9000-9999:9000-9999/udp"